mode: 'evaltest'
checkpoint: 'saved_model/'
fast_ckpt: 'checkpoints/SonyA7S2'
model_name: 'SonyA7S2_DualPathNet_nf48_30M_colortest'
# model_name: 'SonyA7S2_DualPathNet_sharedEnc_nf32_11M'
# TODO:两个模型测试
# model_name: 'SonyA7S2_DualPathNet_ul_share_nf32_17M'
# model_name: 'SonyA7S2_DualPathNet_ul_nf32_depwise_10M'
# model_name: 'SonyA7S2_DualPathNet_ul_indep_24M'
result_dir: 'images/'
num_gpu: 1
num_workers: 8
brightness_correct: True

dst: &base_dst 
  root_dir: '/media/HDD3/personal_files/zhouzhou/VideoDenoisingDatasets/SID'
  bias_dir: 'data/SonyA7S2/bias'
  ds_dir: 'resources/SonyA7S2'
  dataset: 'SID_Dataset' 
  dstname: 'SID'
  command: 'augv2, idremap, darkshading2++'
  # camera_params_file: 'resources/camera_params/camera_params.yaml'
  # use_noise_map: True
  # noise_map_method: 'iso'  # 'iso' 或 'params'
  camera_type: 'SonyA7S2'
  noise_code: 'pgrq'
  patch_size: 512
  H: 2848
  W: 4256
  crop_per_image: 2
  croptype: 'non-overlapping'
  wp: 16383
  bl: 512
  ori: False
  clip: True
  gpu_preprocess: True
dst_train:
  <<: *base_dst
  mode: 'train'
  dataset: 'Mix_Dataset' 
  dstname: 'SID'
dst_eval:
  <<: *base_dst
  root_dir: '/media/HDD3/personal_files/zhouzhou/VideoDenoisingDatasets/ELD/ELD'
  mode: 'eval'
  dataset: 'ELD_Dataset' 
  dstname: 'ELD'
  iso_list: [800, 1600, 3200]
  ratio_list: [100, 200]
dst_test:
  <<: *base_dst
  mode: 'evaltest'
  dataset: 'SID_Dataset' 
  dstname: 'SID'

arch:
  name: 'DPNet_E1'
  # name: 'DualPathUNet_E1_Shared'
  #TODO:
  # name: 'DualPathUNet_E1_Shared_UL'
  # name: 'DualPathNet_UL'
  in_channels: 4
  out_channels: 4
  nf: 48
  use_dpsv: False
  res: False
  cascade: False
  add: False
  lock_wb: False
  heads: [1, 2, 4, 8]
  dilated_rates: [1, 2, 4, 8]
  use_wavelet_upsample: True
  use_sharpness_recovery: True
  use_noise_map: False
  use_texture_detection: True
  enable_intermediate_supervision: True  
  use_depthwise_separable: True

loss:
  perceptual: True  
  gradient: True
  multiloss: False    



hyper:
  lr_scheduler: 'WarmupCosine'
  learning_rate: 2.e-4
  batch_size: 1
  last_epoch: 0
  # last_epoch: -1
  step_size: 10
  stop_epoch : 100
  T: 1
  coldstart: False
  num_workers: 8
  num_gpus: 1
  save_freq: 10
  plot_freq: 50
  best_psnr: 0.